apiVersion: v1
kind: Service
metadata:
  name: keycloak-service-https
  namespace: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
