apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: backstage-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: backstage
    enabled: true
    displayName: Backstage Realm
    groups:
      - name: developers
      - name: platform-engineers
    users:
      - username: dev1
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: dev2
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: dev3
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: pe1
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers
      - username: pe2
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers
      - username: pe3
        enabled: true
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers