apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: backstage-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: backstage
    enabled: true
    displayName: Backstage Realm
    groups:
      - name: developers
      - name: platform-engineers
    users:
      - username: dev1
        enabled: true
        email: dev1@example.com
        emailVerified: true
        firstName: dev1
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: dev2
        enabled: true
        email: dev2@example.com
        emailVerified: true
        firstName: dev2
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: dev3
        enabled: true
        email: dev3@example.com
        emailVerified: true
        firstName: dev3
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - developers
      - username: pe1
        enabled: true
        email: pe1@example.com
        emailVerified: true
        firstName: pe1
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers
      - username: pe2
        enabled: true
        email: pe2@example.com
        emailVerified: true
        firstName: pe2
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers
      - username: pe3
        enabled: true
        email: pe3@example.com
        emailVerified: true
        firstName: pe3
        lastName: Backstage
        credentials:
          - type: password
            value: backstage
            temporary: false
        groups:
          - platform-engineers