---
- name: Eliminar carpeta temporal si ya existe
  ansible.builtin.file:
    path: /tmp/developer-hub
    state: absent

- name: Clonar el repositorio que contiene los manifiestos
  git:
    repo: "{{ gitops_repo }}"
    dest: "{{ gitops_repo_path }}"
    version: main
    force: yes

- name: Renderizar manifiesto de instancia Keycloak con hostname personalizado
  template:
    src: "templates/keycloak-instance.yaml.j2"
    dest: "{{ gitops_repo_path }}/apps/keycloak/overlays/dev/keycloak-instance.yaml"

- name: Aplicar manifiesto de instancia Keycloak
  kubernetes.core.k8s:
    state: present
    src: "{{ gitops_repo_path }}/apps/keycloak/overlays/dev/keycloak-instance.yaml"

- name: Esperar que el pod de Keycloak esté en estado Ready
  shell: |
    oc --context {{ kube_context }} rollout status statefulset/keycloak -n keycloak --timeout=300s
  register: wait_for_pod
  retries: 6
  delay: 10
  until: wait_for_pod.rc == 0

- name: Esperar que el Secret "keycloak-initial-admin" exista
  shell: |
    oc --context {{ kube_context }} -n keycloak get secret keycloak-initial-admin
  register: secret_check
  retries: 10
  delay: 10
  until: secret_check.rc == 0

- name: Resetear import de realm Backstage (si existe)
  kubernetes.core.k8s:
    state: absent
    api_version: k8s.keycloak.org/v2alpha1
    kind: KeycloakRealmImport
    name: backstage-realm
    namespace: keycloak
  ignore_errors: true

- name: Aplicar KeycloakRealmImport (Backstage)
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../../apps/keycloak-realm/overlays/dev/keycloak-realm-import.yaml"

- name: Esperar a que el Job de importación del realm Backstage finalice
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    name: backstage-realm
    namespace: keycloak
  register: backstage_realm_job
  until:
    - backstage_realm_job.resources | length > 0
    - (backstage_realm_job.resources[0].status.succeeded | default(0) | int) >= 1
  retries: 60
  delay: 5