apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
{{- if and .Values.imagePullSecrets.enabled .Values.imagePullSecrets.name }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets.name }}
{{- end }}

