apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-dev-build
  namespace: ${{ values.gitops_namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: ${{ values.gitops_project }}
  source:
    repoURL: ${{ values.source_repository_gitops }}
    targetRevision: HEAD
    path: ./helm/quarkus-rhtap-build
    helm:
      values: |
        nameOverride: ${{ values.component_id }}
        owner: ${{ values.owner }}
        git:
          host: ${{ values.repository_host }}
          appRepo: ${{ values.source_repository }}
          gitopsRepo: ${{ values.source_repository_gitops }}
          branch: main
          gitopsValuesPath: helm/quarkus-rhtap-app/values-dev.yaml
        image:
          registry: ${{values.image_registry}}
          organization: ${{values.image_organization}}
          password: ${{values.image_password}}
          host: ${{ values.image_host }}
          name: ${{ values.image_name }}
          namespace: ${{ values.namespace }}
          tag: ${{ values.image_tag }}
        cluster:
          subdomain: ${{ values.cluster_subdomain }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
