apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhtpa-operator
  namespace: trusted-profile-analyzer
spec:
  channel: stable-v1.1
  name: rhtpa-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

