- name: Regenerar client secret - Obtener info cliente
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ keycloak_client_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
    validate_certs: false
  register: client_info

- name: Crear cliente Backstage si no existe
  when: client_info.json is not defined or client_info.json | length == 0
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients"
    method: POST
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      clientId: "{{ keycloak_client_id }}"
      name: "{{ keycloak_client_id }}"
      enabled: true
      publicClient: false
      serviceAccountsEnabled: true
      standardFlowEnabled: true
      implicitFlowEnabled: false
      directAccessGrantsEnabled: false
      protocol: "openid-connect"
      redirectUris:
        - "*"
      webOrigins:
        - "*"
    status_code: [201, 409]
    validate_certs: false
  register: backstage_client_creation

- name: Regenerar client secret - Re-obtener info cliente
  when: client_info.json is not defined or client_info.json | length == 0
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients?clientId={{ keycloak_client_id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
    validate_certs: false
  register: client_info_after_create

- name: Verificar que el cliente existe
  ansible.builtin.fail:
    msg: "No se encontró el cliente con clientId={{ keycloak_client_id }}"
  when:
    - (client_info_after_create.json is defined and (client_info_after_create.json | length == 0)) or
      (client_info_after_create.json is not defined and (client_info.json is not defined or (client_info.json | length == 0)))

- set_fact:
    client_id_internal: >-
      {{ (client_info_after_create.json[0].id
          if (client_info_after_create is defined and client_info_after_create.json is defined and (client_info_after_create.json | length > 0))
          else client_info.json[0].id) }}

- name: Regenerar client secret
  uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/clients/{{ client_id_internal }}/client-secret"
    method: POST
    headers:
      Authorization: "Bearer {{ kc_token }}"
    status_code: 200
    return_content: true
    validate_certs: false
  register: client_secret_response

- set_fact:
    backstage_client_secret: "{{ client_secret_response.json.value }}"