- name: Crear usuarios en Keycloak
  ansible.builtin.include_tasks: _create-one-user.yaml
  loop: "{{ user_list }}"
  loop_control:
    loop_var: kc_user

- name: Inicializar mapa de IDs de usuarios
  ansible.builtin.set_fact:
    kc_user_ids: {}

- name: Obtener ID de usuarios recién creados
  ansible.builtin.include_tasks: _lookup-one-user.yaml
  loop: "{{ user_list }}"
  loop_control:
    loop_var: kc_user

- name: Obtener ID del grupo {{ group_name }}
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/groups"
    method: GET
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    return_content: true
    validate_certs: false
    status_code: 200
  register: groups_result
  retries: 5
  delay: 10
  until: groups_result.status == 200
  
- name: Setear ID del grupo
  ansible.builtin.set_fact:
    current_group_id: >-
      {{
        (groups_result.json | selectattr('name', 'equalto', group_name) | list)[0].id
      }}

- name: Asociar usuarios al grupo {{ group_name }}
  ansible.builtin.uri:
    url: "https://{{ keycloak_hostname }}/admin/realms/{{ keycloak_realm }}/users/{{ kc_user_ids[item.username] }}/groups/{{ current_group_id }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ kc_token }}"
      Content-Type: "application/json"
    status_code: 204
    validate_certs: false
  loop: "{{ user_list }}"
  loop_control:
    loop_var: item