---
- name: "Crear namespace 'neuralbank'"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: neuralbank

- name: "Eliminar rastro de importación anterior (Forzar re-import)"
  kubernetes.core.k8s:
    state: absent
    api_version: k8s.keycloak.org/v2alpha1
    kind: KeycloakRealmImport
    name: neuralbank-full-import
    namespace: keycloak
  ignore_errors: yes

- name: "Importar Realm 'neuralbank' en Keycloak"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'templates/neuralbank-realm.yaml.j2') }}"

- name: "Esperar a que la importación del Realm finalice"
  kubernetes.core.k8s_info:
    api_version: k8s.keycloak.org/v2alpha1
    kind: KeycloakRealmImport
    name: neuralbank-full-import
    namespace: keycloak
  register: realm_import_status
  until: 
    - realm_import_status.resources | length > 0
    - realm_import_status.resources[0].status.conditions is defined
    - realm_import_status.resources[0].status.conditions | selectattr('type', 'equalto', 'Done') | selectattr('status', 'equalto', 'True') | list | length > 0
  retries: 60
  delay: 5

- name: Establecer variable con el secreto del cliente NeuralBank
  ansible.builtin.set_fact:
    neuralbank_frontend_secret: "{{ neuralbank_frontend_client_secret }}"

- name: "Crear Secret 'neuralbank-oidc-secret' en namespace neuralbank"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: neuralbank-oidc-secret
        namespace: neuralbank
      type: Opaque
      stringData:
        client-secret: "{{ neuralbank_frontend_secret }}"