apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  tags: [java, spring, spring-boot, webflux, async-api, sse]
  annotations:
    # --- GitOps y Kubernetes ---
    argocd/app-selector: rht-gitops.com/${{ values.gitops_namespace }}=${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    backstage.io/source-location: url:https://${{ values.host }}/${{ values.destination }}
    backstage.io/techdocs-ref: url:https://${{ values.host }}/${{ values.destination }}
    gitlab.com/project-slug: ${{ values.destination }}
    jenkins.io/job-full-name: ${{ values.jenkins_job_name }}
    jenkins.io/instance: default
spec:
  type: service
  lifecycle: development
  owner: group:default/${{ values.owner }}
  providesApis:
    - ${{ values.component_id }}-http-api
    - ${{ values.component_id }}-events-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-http-api
  description: Payments HTTP API (submit + status)
  tags: [openapi, async, sse, payments]
  annotations:
    backstage.io/source-location: url:https://${{ values.host }}/${{ values.destination }}
spec:
  type: openapi
  lifecycle: development
  owner: group:default/${{ values.owner }}
  definition:
    $text: ./openapi.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.component_id }}-events-api
  description: Payments events stream (SSE) documented with AsyncAPI
  tags: [asyncapi, async, sse, payments, events]
  annotations:
    backstage.io/source-location: url:https://${{ values.host }}/${{ values.destination }}
spec:
  type: asyncapi
  lifecycle: development
  owner: group:default/${{ values.owner }}
  definition:
    $text: ./asyncapi.yaml

