pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Test') {
      steps {
        sh 'mvn -B -ntp test'
      }
    }
    stage('Package') {
      steps {
        sh 'mvn -B -ntp package -DskipTests'
      }
    }
  }
}

