- hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/demo.yaml

  vars:
    kube_context: "{{ lookup('env','K8S_AUTH_CONTEXT') | default('previred', true) }}"
    enable_ai_stack: "{{ lookup('env','ENABLE_AI_STACK') | default(false, true) }}"
    enable_jenkins: "{{ lookup('env','ENABLE_JENKINS') | default(true, true) }}"
    enable_service_mesh: "{{ lookup('env','ENABLE_SERVICE_MESH') | default(true, true) }}"
    enable_rhtpa: "{{ lookup('env','ENABLE_RHTPA') | default(false, true) }}"

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    k8s:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    k8s_info:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
  
  roles:
    - role: openshift-config
    - role: gitops-config
    - role: gitops-deploy-pipelines
    - role: gitops-deploy-tekton-chains
    - role: gitops-deploy-jenkins
      when: enable_jenkins | bool
    - role: gitops-devspaces
    - role: gitops-deploy-vault-operator
    - role: gitops-deploy-keycloak
    - role: keycloak-config
    - role: gitops-deploy-rhtas
    - role: gitops-deploy-enterprise-contract
    - role: gitops-deploy-rhtpa
      when: enable_rhtpa | bool
    - role: gitops-deploy-gitlab
    - role: gitops-deploy-odf
    - role: gitops-deploy-quay
    - role: gitlab-config
    - role: gitops-deploy-developer-hub
    - role: gitops-observability
    - role: gitops-logging
    - role: gitops-deploy-neuralbank
      when: enable_service_mesh | bool
    - role: gitops-deploy-kiali
      when: enable_service_mesh | bool
    - role: gitops-deploy-kubernetes-mcp
      when: enable_ai_stack | bool
    - role: gitops-deploy-openshift-lightspeed
      when: enable_ai_stack | bool
    - role: dashboard
