- hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/demo.yaml

  vars:
    kube_context: "{{ lookup('env','K8S_AUTH_CONTEXT') | default('previred', true) }}"

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    kubernetes.core.k8s_info:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    k8s:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
    k8s_info:
      kubeconfig: "{{ lookup('env','KUBECONFIG') }}"
      context: "{{ kube_context }}"
  
  roles:
    - role: openshift-config
    - role: gitops-config
    - role: gitops-deploy-jenkins
    - role: gitops-devspaces
    - role: gitops-deploy-vault-operator
    - role: keycloak-config
    - role: gitops-deploy-gitlab
    - role: gitops-deploy-odf
    - role: gitops-deploy-quay
    - role: gitlab-config
    - role: gitops-deploy-developer-hub
    - role: gitops-observability
    - role: gitops-logging
    - role: gitops-deploy-neuralbank
    - role: gitops-deploy-kiali
    - role: gitops-deploy-kubernetes-mcp
    - role: gitops-deploy-openshift-lightspeed
    - role: dashboard
