apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuralbank-app-writer
  namespace: neuralbank
rules:
  - apiGroups:
      - "" 
    resources:
      - services
      - secrets
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kuadrant.io
    resources:
      - authpolicies
      - kuadrants
      - ratelimitpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions.kuadrant.io
    resources:
      - oidcpolicies 
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuralbank-app-binding
  namespace: neuralbank
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: neuralbank-app-writer
  apiGroup: rbac.authorization.k8s.io
