apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_id }}
  description: ${{ values.description }}
  tags: [go, gin, rest, neuralbank]
spec:
  type: service
  lifecycle: experimental
  owner: group:default/${{ values.owner }}
  system: neuralbank-digital-channels
