apiVersion: extensions.kuadrant.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: neuralbank-oidc
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    issuerURL: "https://sso.apps.ocp.ccld9.sandbox1286.opentlc.com/realms/neuralbank"
    clientID: "neuralbank-frontend" 
    clientSecretRef:
      name: neuralbank-oidc-secret
      key: client-secret

    authorizationEndpoint: "https://sso.apps.ocp.ccld9.sandbox1286.opentlc.com/realms/neuralbank/protocol/openid-connect/auth"
    redirectURI: "https://neuralbank.apps.ocp.ccld9.sandbox1286.opentlc.com/auth/callback"
    tokenEndpoint: "https://sso.apps.ocp.ccld9.sandbox1286.opentlc.com/realms/neuralbank/protocol/openid-connect/token"
   
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: neuralbank-api-route

  auth:
    tokenSource:
      authorizationHeader:
        prefix: Bearer
        name: Authorization
      cookie:
        name: jwt