apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-service
  description: API del servicio de clientes de Neuralbank
  tags:
    - openapi
    - core
spec:
  type: openapi
  lifecycle: production
  owner: group:default/platform-engineers
  system: neuralbank-customers
  definition:
    $text: ./openapi.yaml
