apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: neuralbank-external-route
  namespace: istio-system
  annotations:
    haproxy.router.openshift.io/timeout: 300s
spec:
  host: "neuralbank.apps.ocp.mm727.sandbox944.opentlc.com"
  to:
    kind: Service
    name: neuralbank-gateway-istio
    weight: 100
  port:
    targetPort: http 
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect