kind: Istio
apiVersion: sailoperator.io/v1
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  namespace: istio-system
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  version: v1.26.2
---
kind: IstioCNI
apiVersion: sailoperator.io/v1
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  namespace: istio-system
  version: v1.26.2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-sail-operator-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
- apiGroups:
  - sailoperator.io
  resources:
  - istios
  - istios/finalizers
  - istios/status
  - istiocnis
  - istiocnis/finalizers
  - istiocnis/status 
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
    - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-sail-operator-binding
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-sail-operator-manager 
