apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
    app.openshift.io/runtime: spring-boot
    app.kubernetes.io/part-of: ${{ values.component_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${{ values.component_id }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${{ values.component_id }}
        backstage.io/kubernetes-id: ${{ values.component_id }}
        app.openshift.io/runtime: spring-boot
        app.kubernetes.io/part-of: ${{ values.component_id }}
    spec:
      containers:
        - name: app
          image: image-registry.openshift-image-registry.svc:5000/${{ values.namespace }}/${{ values.component_id }}:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20

