apiVersion: v1
kind: Service
metadata:
  name: ${{ values.component_id }}
  labels:
    app.kubernetes.io/name: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
spec:
  selector:
    app.kubernetes.io/name: ${{ values.component_id }}
  ports:
    - name: http
      port: 80
      targetPort: 8080

