apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sigstore-keyless-external
spec:
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: sigstore-keyless
  data:
    - secretKey: client_id
      remoteRef:
        key: secrets/rhdh/sigstore_keyless
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: secrets/rhdh/sigstore_keyless
        property: client_secret
    - secretKey: username
      remoteRef:
        key: secrets/rhdh/sigstore_keyless
        property: username
    - secretKey: password
      remoteRef:
        key: secrets/rhdh/sigstore_keyless
        property: password

