apiVersion: v1
kind: Secret
metadata:
  name: quay-dockerconfig
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{
    printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
      .Values.image.host
      .Values.image.organization
      .Values.image.password
      (printf "%s:%s" .Values.image.organization .Values.image.password | b64enc)
    | b64enc
  }}

